name: Run Code

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run JavaScript code
        env:
          CSV_TOKEN: ${{ secrets.CSV_TOKEN }}
        run: node code.js
